### PR TITLE
Update debian version

### PR DESCRIPTION
**Pull request by guillaume-gambs**
Change version of debian repository, and fix mysql package name

### CODE REVIEW

**Comment by selim13** [comment]
Hey! Thanks for noticing incorrect debian version.
But why should we change the package name? 
`mysql-community-client-core` contains `mysql` and  `mysqldump`  which are automysqlbackup's only dependencies, while `mysql-community-client` installs more advanced utilities like `mysqladmin`, man pages, and all sorts of things which we don't really require in the image.

**Comment by guillaume-gambs** [comment]
Hello, You are welcome ! ;)

Thanks for the repository ! 

Because my build works , and with , it will say `E: Unable to locate package mysql-community-client-core`

For information I set my env `MYSQL_MAJOR` to `5.7`

**Comment by selim13** [comment]
Ah, I see. mysql 5.7 didn't have `-core` version of the client package.
I think a better solution will be creating separate branch and image for automysqlbackup with mysql 5.7 then.

Can you adjust this pull request to remove package name changing? After merging I will setup a separate build process for 5.7

**Comment by selim13** [comment]
`2.6-9-mysql57` should be available now

**Pull request merged**
